import { Geist, Geist_Mono, Inter, Gabarito } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap", // Improves font loading performance
});

const gabarito = Gabarito({
  variable: "--font-gabarito",
  subsets: ['latin'], // Include only the subsets you need
});

export const metadata = {
  title: "eRuchi",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
